/**
 * Generates real-geometry SVG path data for the Maps module from public
 * GeoJSON sources (run: node scripts/gen-geo.mjs <downloads-dir>).
 *
 * Sources (downloaded separately, see URLs below):
 *  - probe-india.json      adarshbiradar/maps-geojson (37 states/UTs incl.
 *                          Telangana & Ladakh, Survey-of-India full-claim J&K)
 *  - bihar-districts.geojson  udit-001/india-maps-data (38 Bihar districts)
 *
 * Output: src/components/maps/geo/indiaStates.ts, biharDistricts.ts
 * Both share an equirectangular projection whose params are exported so
 * thematic layers can plot rivers/cities by real lon/lat.
 */
import fs from 'fs';
import path from 'path';

const dir = process.argv[2];
if (!dir) throw new Error('usage: node scripts/gen-geo.mjs <dir-with-downloaded-geojson>');

// --- Douglas-Peucker simplification (on projected coords) ---
function simplify(pts, tol) {
  if (pts.length <= 3) return pts;
  const keep = new Array(pts.length).fill(false);
  keep[0] = keep[pts.length - 1] = true;
  const stack = [[0, pts.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop();
    let maxD = 0, idx = -1;
    const [ax, ay] = pts[a], [bx, by] = pts[b];
    const dx = bx - ax, dy = by - ay;
    const len2 = dx * dx + dy * dy || 1e-12;
    for (let i = a + 1; i < b; i++) {
      const [px, py] = pts[i];
      const t = Math.max(0, Math.min(1, ((px - ax) * dx + (py - ay) * dy) / len2));
      const ex = ax + t * dx - px, ey = ay + t * dy - py;
      const d = ex * ex + ey * ey;
      if (d > maxD) { maxD = d; idx = i; }
    }
    if (Math.sqrt(maxD) > tol) {
      keep[idx] = true;
      stack.push([a, idx], [idx, b]);
    }
  }
  return pts.filter((_, i) => keep[i]);
}

function makeProjector(minLon, maxLon, minLat, maxLat, width) {
  const midLat = (minLat + maxLat) / 2;
  const kx = Math.cos((midLat * Math.PI) / 180);
  const spanX = (maxLon - minLon) * kx;
  const spanY = maxLat - minLat;
  const scale = width / spanX;
  const height = spanY * scale;
  const project = (lon, lat) => [
    +(((lon - minLon) * kx) * scale).toFixed(1),
    +(((maxLat - lat)) * scale).toFixed(1),
  ];
  return { project, width, height: Math.ceil(height), params: { minLon, maxLat, kx, scale } };
}

function ringsOf(geom) {
  if (geom.type === 'Polygon') return geom.coordinates;
  if (geom.type === 'MultiPolygon') return geom.coordinates.flat();
  return [];
}

function featureExtent(features) {
  let minLon = 999, maxLon = -999, minLat = 999, maxLat = -999;
  for (const f of features)
    for (const ring of ringsOf(f.geometry))
      for (const [lon, lat] of ring) {
        if (lon < minLon) minLon = lon;
        if (lon > maxLon) maxLon = lon;
        if (lat < minLat) minLat = lat;
        if (lat > maxLat) maxLat = lat;
      }
  return { minLon, maxLon, minLat, maxLat };
}

function toPaths(features, nameProp, proj, tol, minRingPts = 4) {
  return features.map((f) => {
    const name = f.properties[nameProp];
    const parts = [];
    for (const ring of ringsOf(f.geometry)) {
      let pts = ring.map(([lon, lat]) => proj.project(lon, lat));
      pts = simplify(pts, tol);
      if (pts.length < minRingPts) continue;
      parts.push('M' + pts.map((p) => `${p[0]} ${p[1]}`).join('L') + 'Z');
    }
    return { n: name, d: parts.join('') };
  }).filter((s) => s.d);
}

function emit(file, banner, viewBox, params, exportName, shapes) {
  const body =
    `// AUTO-GENERATED by scripts/gen-geo.mjs — do not edit by hand.\n// ${banner}\n` +
    `export const ${exportName}_VIEWBOX = '${viewBox}';\n` +
    `/** Equirectangular projection params: [x,y] = [((lon-minLon)*kx)*scale, (maxLat-lat)*scale] */\n` +
    `export const ${exportName}_PROJ = { minLon: ${params.minLon}, maxLat: ${params.maxLat}, kx: ${params.kx.toFixed(6)}, scale: ${params.scale.toFixed(4)} };\n` +
    `export interface GeoShape { n: string; d: string }\n` +
    `export const ${exportName}: GeoShape[] = ${JSON.stringify(shapes)};\n`;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, body);
  console.log(file, Math.round(body.length / 1024) + 'KB', shapes.length, 'shapes');
}

// ---------------- India states ----------------
{
  const gj = JSON.parse(fs.readFileSync(path.join(dir, 'probe-india.json')));
  const feats = gj.features;
  const ext = featureExtent(feats);
  const proj = makeProjector(ext.minLon, ext.maxLon, ext.minLat, ext.maxLat, 640);
  const shapes = toPaths(feats, 'st_nm', proj, 0.7);
  emit(
    'src/components/maps/geo/indiaStates.ts',
    'Source: adarshbiradar/maps-geojson (MIT), Survey-of-India-style full J&K/Ladakh depiction.',
    `0 0 ${proj.width} ${proj.height}`,
    proj.params,
    'INDIA_STATES',
    shapes
  );
}

// ---------------- Bihar districts ----------------
{
  const gj = JSON.parse(fs.readFileSync(path.join(dir, 'bihar-districts.geojson')));
  const feats = gj.features;
  const ext = featureExtent(feats);
  const proj = makeProjector(ext.minLon, ext.maxLon, ext.minLat, ext.maxLat, 640);
  const shapes = toPaths(feats, 'district', proj, 1.2);
  emit(
    'src/components/maps/geo/biharDistricts.ts',
    'Source: udit-001/india-maps-data (census 2011 districts of Bihar).',
    `0 0 ${proj.width} ${proj.height}`,
    proj.params,
    'BIHAR_DISTRICTS',
    shapes
  );
}
